In [1]:
numpy __version__

SyntaxError: invalid syntax (Temp/ipykernel_9344/1463539639.py, line 1)

In [2]:
import numpy as np

In [5]:
mylist= [1,2,3]

In [6]:
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3])

In [8]:
 mylist

[1, 2, 3]

In [9]:
myarr=np.array(mylist)


In [10]:
myarr

array([1, 2, 3])

In [11]:
type(myarr)

numpy.ndarray

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.random.seed(42)
np.random.randint(0,10,(2,1))

array([[6],
       [3]])

In [21]:
np.random.seed(42)
np.random.randint(0,10,(2,2))

array([[6, 3],
       [7, 4]])

In [14]:
np.random.seed(42)
np.random.randint(0,10,(2,1))

array([[6],
       [3]])

In [36]:
np.random.randint(0,10,(2,2))


array([[4, 6],
       [9, 2]])

In [37]:
np.random.seed(42)
np.random.randint(0,10,(2,2))

array([[6, 3],
       [7, 4]])

In [39]:
np.random.rand(2,2)


array([[0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [40]:
np.random.randn(2,2)


array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975]])

In [51]:
myarray = np.linspace(0,10,101)

In [53]:
len(myarray)

101

In [54]:
a=np.arange(0,8)

In [55]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
a[7]

7

In [59]:
arr2d=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[1][1]

5

In [62]:
arr2d[1]

array([4, 5, 6])

In [68]:
arr2d[:,0]

array([1, 4, 7])

In [77]:
arr2d[1:3,1:]

array([[5, 6],
       [8, 9]])

In [78]:
arr2d>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [79]:
arr2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [80]:
arr2d[arr2d>5]

array([6, 7, 8, 9])

In [81]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr2d[arr2d>9]

array([], dtype=int32)

In [84]:
arr2d.shape

(3, 3)

In [87]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d.sum(axis=1)

array([10, 26, 42])